version: "3.7"

services:
  api:
    build: .
    command: uvicorn delivery.main:app --host 0.0.0.0 --port 8081 --reload
    ports:
      - 8081:8081
    volumes:
      - .:/fastapi_delivery
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
