# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: FastAPI Unit Tests

on: [push]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build containers
      run: |
        docker-compose -f docker-compose.dev.yml build
        docker-compose -f docker-compose.dev.yml pull
    - name: Run tests
      run: |
        docker-compose -f docker-compose.dev.yml up --force-recreate --remove-orphans -d
        export ID=$(docker-compose -f docker-compose.dev.yml ps -q api)
        docker exec ${ID} delivery/test.sh -vv
